language: php
php:
  - 7.1.9
  - 7.2
  - 7.3
  - 7.4
before_script:
  - travis_retry composer self-update
install:
  - composer install --prefer-source --no-interaction
script:
  - phpunit --coverage-clover=coverage.xml
  - vendor/bin/php-cs-fixer fix --dry-run
after_success:
  - bash <(curl -s https://codecov.io/bash)
