on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          extensions: "xdebug-beta"
      - name: Report PHP version
        run: php -v
      - name: Install dependencies
        run: composer install
      - name: Run test suite
        run: vendor/bin/phpunit
      - name: Run code fixer
        run: vendor/bin/php-cs-fixer fix --dry-run
